export const SKILLS_REGEX = {
  AGILE: [/agile/i, /scrum/i, /kanban/i, /pair programming/i, /clean architectures/i, /(metodologia(s)?|desenvolvimento) ag(eis|il)/i],
  ANGULAR: [/\bangular\b/i],
  ANTD: [/ant( |-)?(d(esign)?)/i],
  AJAX: [/\bajax\b/i],
  API: [/(api(s)?)?rest(ful)?( api(s)?)?/i, /\bapi(s)?\b/i, /soap/i, /graphql/],
  APOLLO: [/apollo/i],
  BACHELORS_DEGREE: [/bachelor's degree/i, /computer science/i, /bacharelado/i, /ciencia da computacao/i, /(gradua(do|cao)|superior) complet(a|o)/i, /(ensino|formacao) superior/i],
  COBOL: [/cobol/i],
  CODE_MAINTAINABILITY: [/eslint/i, /prettier/i],
  CODE_VERSIONING: [/\bgit((-| )?(hub|lab)?)?\b/i, /bitbucket/i, /\bsvn\b/i, /controle de versionamento/i, /version control/i],
  C: [/\bc\b/i],
  CPLUSPLUS: [/c\+\+/i],
  CSHARP: [/c#/i],
  CSS: [/\b(s)?css(3)?\b/i],
  DART: [/dart/i],
  DB: [/banco de dados/i, /mongo( )?db/i, /\b(ms-|microsoft )?sql(-| )?(server)?\b/i, /postgre(s)?/i, /my( )?sql/i, /firebase/i, /redis/i, /no( )?sql/i, /\borm\b/i, /oracle/i],
  DELPHI: [/delphi/i],
  DEV_OPS: [/docker/i, /aws/i, /kubernetes/i, /terraform/i, /azure/i, /jenkins/i, /ci(\/|-| )?cd/i, /container(s)?/i, /devops/i, /git(-| )?(hub)?(-| )actions/i, /lambda(s)?/i, /\becs\b/i],
  DJANGO: [/django/i],
  DOT_NET: [/\.net/i],
  ECOMMERCE: [/shop(i)?fy/i, /\blinx\b/i, /\btray(corp)?\b/i],
  ENGLISH: [/ingles/i, /english/i],
  FIGMA: [/figma/i],
  FLUTTER: [/flutter/i],
  FRONTEND_BUILD_TOOLS: [/webpack/i, /babel/i, /\bnpm\b/i, /\byarn\b/i],
  FULL_STACK: [/full(-| )?stack/i],
  GOLANG: [/golang/i],
  HTML: [/html(5)?/i],
  IONIC: [/ionic/i],
  JAVA: [/\bjava\b/i],
  JAVASCRIPT: [/java( |-)?script/i, /^(.|-)?js\b/i, /\bes6\b/i],
  JQUERY: [/jquery/i],
  KOTLIN: [/kotlin/i],
  LINUX: [/linux/i],
  MACHINE_LEARNING: [/machine learning/i],
  MATERIAL_UI: [/\bm(aterial)?(-| )?ui\b/i],
  NEXT: [/\bnext((.|-| )?js)?\b/i],
  NUXT: [/\bnuxt((.|-| )?js)?\b/i],
  NODE: [/\bnode((.|-| )?js)?\b/i],
  PHP: [/php/i, /laravel/i, /symfony/i],
  POWER_BI: [/power( )?bi/i],
  PYTHON: [/python/i, /phyton/i],
  PWA: [/pwa/i],
  REACT: [/\breact((.|-| )?js)?\b/i],
  REACT_NATIVE: [/react(-| )?native/i],
  REACT_ROUTER: [/react router/i],
  RESPONSIVE_DESIGN: [/design responsivo/i, /site(s)? responsivo(s?)/i, /responsividade/i, /mobile first/i],
  RUBY: [/\bruby((-| )on(-| )rails)?/i, /rails/i],
  RUST: [/\brust\b/i],
  SASS: [/\bsass\b/i],
  SALESFORCE: [/salesforce/i],
  SCALA: [/\bscala\b/i],
  STATE_MANAGEMENT: [/redux/i, /mobx/i, /state management/i, /bibliotecas de gerenciamento de estado/i, /recoil/i],
  STORYBOOK: [/storybook/i],
  STYLED_COMPONENTS: [/styled(-| )?component(s)?/i],
  SWIFT: [/\bswift\b/i],
  TAILWIND: [/\btailwind(-| )?(css)?\b/i],
  TEST: [
    /jest/i, /cypress/i, /\btdd\b/i, /\be2e\b/i,
    /teste(s)?(\b| )((funciona(is|l) )?(unitario|automatizado)(s)?)?/i,
    /teste(s)? (d)?e (unidade|integracao|software|performance|depuracao)/i, /enzyme/i, /react testing library/i, /mocha/i,
    /testing( practices)?/i, /code coverage/i,
  ],
  TYPESCRIPT: [/type( |-)?script/i, /\bts\b/i],
  VANILLA: [/((javascript|js) )?vanilla(.|-| )?(js|javascript)?/i],
  VUE: [/\bvue((.|-| )?js)?\b/i],
  WEB_HOOKS: [/web( )?hook(s)?/i],
  WORDPRESS: [/wordpress/i],
}

export const BENEFITS_REGEX = {
  ANUAL_BONUS: [/bonus anual/i, /bonus per year/i, /bonificacao anual/i, /annual bonus/i],
  BIRTHDAY_DAYOFF: [/day off de aniversario/i, /day off/i, /day-off/i, /dia de folga na semana do seu aniversario/i, /dayOff no mes do aniversario/i],
  COURSE_HELP: [
    /curso de aperfeiçoamento profissional/i, /learning and development support/i, /investimento em cursos/i, /incentivo a estudos/i, /programa de capacitacao/i,
    /alura/i, /acesso a cursos/i, /curso de/i, /aquisicao de livros e cursos/i, /subsidio para estudo/i, /auxilio educacao/i, /auxilio educacao/i,
    / incentivo para educacao/i
  ],
  FLEXIBLE_HOURS: [/horarios flexiveis/i, /horario flexivel/i, /flexible hours/i, /flexibilidade de horario/i, /flexible schedule/i, /flexible working schedules/i],
  GYMPASS: [/gympass/i, /academia/i, /gym pass/i, /auxilio academia/i, /totalpass/i],
  HEALTH_OR_DENTAL_PLAN: [
    /plano odontologico/i, /convenio odontologico/i, /convenio medico e odontologico/i,
    /plano de saude e odontologico/i, /assistencia medica e odontologica/i, /dental/i, /assistencia odontologica/i,
    /assistencias medica e odontologica/i,
    /plano de saude/i, /convenio saude/i, /convenio medico e odontologico/i, /plano de saude e odontologico/i, /assistencia medica e odontologica/i,
    /health care/i, /assistencia medica/i, /convenio medico/i, /health insurance/i, /health plan/i, /health and dental plan/, /assistencias medica e odontologica/i
  ],
  HOME_OFFICE_VOUCHER: [/auxilio home office/i, /subsidio para trabalho remoto/i, /auxilio home-office/i, /auxilio para atuacao em home office/i, /remote work allowance/i, /auxilio para trabalho remoto/i],
  LIFE_INSURANCE: [/seguro de vida/i, /life insurance/i],
  MEAL_VOUCHER: [/alimentacao/i, /refeicao/i, /caju/i, /\bva\b/i, /\bvr\b/i, /flex food/i, /to use with food/i],
  PAID_VACATIONS: [/ferias remuneradas/i, /ferias anuais remuneradas/i, /descanso anual/i, /descanso remunerado/i, /paid annual leave/i, /interrupcao remunerada do contrato/i, /ferias remunerada/i, /ferias e feriados remunerados/i],
  PRIVATE_PENSION: [/previdencia privada/i],
  PSYCHOLOGICAL_HELP: [/auxilio psicologico/i, /apoio psicologico/i, /mental health/i, /apoio à saude mental/i, /cuidado com saude mental/i, /auxilio saude emocional/i, /auxilio bem estar/i, /suporte social e psicologico/i],
  REFERRAL_BONUS: [/bônus indicacao/i, /program of indication/i, /indicacao premiada/i, /bônus por indicacao de talentos/i],
  STOCK_OPTIONS: [/stock options/i],
  TRANSPORTATION_VOUCHER: [/vale transporte/i],
  USD_SALARY: [/salary in usd/i],
}

export const HIRING_REGIMES_REGEX = {
  CLT: [/\bclt\b/i],
  PJ: [/\bpj\b/i, /pessoa juridica/i],
}

export const TYPES_REGEX = {
  REMOTE: [/home(-| )?office/i, /\bremoto\b/i, /trabalhar de casa/i, /\bremote\b/i, /\bremota\b/i],
  HYBRID: [/hibrido/i, /hybrid/i],
  FACE_TO_FACE: [/presencial/i],
}